### ISSUE TITLE
unable to start /opt/networkoptix/mediaserver/bin/mediaserver-bin (Invalid argument)

### ISSUE THREAD

**Issue by ptr727** [thehomerepot/nxwitness#15]
I am unable to get the nxwitness or digitalwatchdog aps to run in the container.

DWSpectrum:
```
--- Starting: /opt/digitalwatchdog/mediaserver/bin/mediaserver-bin -e --crash-directory=/opt/digitalwatchdog/mediaserver/var/crash
start-stop-daemon: unable to start /opt/digitalwatchdog/mediaserver/bin/mediaserver-bin (Invalid argument)
```

NxWitness:
```
--- Starting: /opt/networkoptix/mediaserver/bin/mediaserver-bin -e --crash-directory=/opt/networkoptix/mediaserver/var/crash
start-stop-daemon: unable to start /opt/networkoptix/mediaserver/bin/mediaserver-bin (Invalid argument)
```

I am playing around with LSIO, and learning about systemd, and I used your modifications [here](https://github.com/ptr727/DWSpectrum-LSIO) and the NxWitness systemd version [here](https://github.com/ptr727/DWSpectrum)

Neither my LSIO version nor your version seem to run?
The systemd version does run, but only if run as root, I can't get it to run using --user.

I am using this compose, and I am building on Ubuntu Server LTS, using VSCode over SSH:
```yaml
version: "3.7"

services:
  dwspectrum:
    image: nxwitness
    container_name: nxwitness-test-container
    hostname: nxwitness-test-host
    domainname: foo.bar
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Americas/Los_Angeles
    build: .
    volumes:
      - ./.mount/media:/archive
      - ./.mount/config:/config
    #restart: unless-stopped
    network_mode: host
    ports:
      - 7001:7001
```
Any ideas?

**Comment by thehomerepot** [comment]
When you say "Neither my LSIO version nor your version seem to run?", are you saying my actual docker container images, or the one you modified based on mine?

**Comment by ptr727** [comment]
I git cloned your project, and then compose up, other than using my compose file, I did not make changes to your code.
I have not tested the pre-built container on docker hub.

**Comment by thehomerepot** [comment]
It looks like the dockerfile was re-organized and modified from mine. As this is an issues list for my releases, please test using my docker container.

**Comment by ptr727** [comment]
Sorry, I was probably not clear in my previous reply, I did test using your code, I git cloned this project.
I just tested with the image on docker hub, same problem.
Maybe there is something in my config that is causing the issue, but what?

Compose:
```yaml
version: "3.7"

services:
  dwspectrum:
    #image: nxwitness
    image: thehomerepot/nxwitness
    container_name: nxwitness-test-container
    hostname: nxwitness-test-host
    domainname: foo.bar
    environment:
      #- PUID=1000
      #- PGID=1000
      - TZ=Americas/Los_Angeles
    build: .
    volumes:
      - ./.mount/media:/archive
      - ./.mount/config:/config
    #restart: unless-stopped
    network_mode: host
    ports:
      - 7001:7001
```

Logs output:
```
pieter@docker:~/repos/nxwitness$ docker logs -f b7b96622aa31ea3ea6208b6f8546ce6767fbb97226814a55fe0d24885c2caf3c
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-relocate-files: executing... 
[cont-init.d] 50-relocate-files: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting root_tool, using domain socket: /tmp/networkoptix_syscmd_socket3f64fa
[services.d] done.
/opt/networkoptix/mediaserver/bin/mediaserver: line 41: /proc/sys/net/ipv4/conf/all/rp_filter: Read-only file system
/opt/networkoptix/mediaserver/bin/mediaserver: line 41: /proc/sys/net/ipv4/conf/default/rp_filter: Read-only file system
/opt/networkoptix/mediaserver/bin/mediaserver: line 41: /proc/sys/net/ipv4/conf/docker0/rp_filter: Read-only file system
/opt/networkoptix/mediaserver/bin/mediaserver: line 41: /proc/sys/net/ipv4/conf/ens3/rp_filter: Read-only file system
/opt/networkoptix/mediaserver/bin/mediaserver: line 41: /proc/sys/net/ipv4/conf/lo/rp_filter: Read-only file system
/usr/bin/gdb

--- Set ulimits:
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15396
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 15396
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

--- Starting: /opt/networkoptix/mediaserver/bin/mediaserver-bin -e --crash-directory=/opt/networkoptix/mediaserver/var/crash
start-stop-daemon: unable to start /opt/networkoptix/mediaserver/bin/mediaserver-bin (Invalid argument)
pieter@docker:~/repos/nxwitness$ 
```
