### ISSUE TITLE
Unable to see storage

### ISSUE THREAD

**Issue by brendandodd** [thehomerepot/nxwitness#17]
Have mapped /archive path to share, setup UID an GID etc.
/config directory is working fine, has permissions etc.

Container console shows permissions OK on /archive

No storage locations present in client, cannot add external storage.

Is there something I'm missing?

**Comment by thehomerepot** [comment]
You'll have to work with Network Optix for issues with storage locations, especially a network share. It's notoriously finicky with what it will accept as storage.

For reference though, here is my docker-compose entry.
```
    nxwitness:
        image: thehomerepot/nxwitness:4.0.0.30434
        container_name: nxwitness
        restart: unless-stopped
        network_mode: host
        volumes:
         - ${DOCKER_CONFIG}/nxwitness/config:/config
         - /mpool01/media/nvr/nxwitness:/archive/HD Witness Media
        environment:
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=America/Chicago
         - LISTEN_PORT=7001
```
